import Head from "next/head";
import Link from "next/link";
import Layout from "../components/layout/layout";
import { useSession, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();

  return (
    <Layout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{session ? User({ session }) : Guest()}</div>
    </Layout>
  );
}

function Guest() {
  return (
    <div>
      <h2>Guest Page</h2>

      <div>
        <Link href="/login">Sign In</Link>
      </div>
    </div>
  );
}

function User({ session }: any) {
  return (
    <div>
      <h2>Authorized user Page</h2>

      <div>
        <h4>User: {session.user.name}</h4>
        <h4>Email: {session.user.email}</h4>
      </div>

      <div>
        <button onClick={() => signOut()}>Sign Out</button>
      </div>

      <div>
        <Link href="/profile">Profile</Link>
      </div>
    </div>
  );
}
