import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Layout from "../components/layout/layout";

export default function Home() {
  const [session, setSession] = useState<boolean>(false);

  return (
    <Layout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{session ? User() : Guest()}</div>
    </Layout>
  );
}

function Guest() {
  return (
    <div>
      <h2>Guest Page</h2>

      <div>
        <Link href="/login">Sign In</Link>
      </div>
    </div>
  );
}

function User() {
  return (
    <div>
      <h2>Authorized user Page</h2>

      <div>
        <h4>User:</h4>
        <h4>Email:</h4>
      </div>

      <div>
        <button>Sign Out</button>
      </div>

      <div>
        <Link href="/profile">Profile</Link>
      </div>
    </div>
  );
}
