import Head from "next/head";
import Link from "next/link";
import React from "react";
import Layout from "../components/layout/layout";
import { signIn } from "next-auth/react";

const Login = () => {
  return (
    <Layout>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Login</h1>

      <div>
        <form>
          <div>
            <input type="email" name="email" placeholder="email" />
          </div>
          <div>
            <input type="password" name="password" placeholder="password" />
          </div>
          <div>
            <button type="submit">Login</button>
          </div>
          <hr />
          <div>
            <div>
              <button
                onClick={() =>
                  signIn("google", { callbackUrl: "http://localhost:3000" })
                }
                type="button"
              >
                Sign In with Google
              </button>
            </div>
            <div>
              <button
                onClick={() =>
                  signIn("github", { callbackUrl: "http://localhost:3000" })
                }
                type="button"
              >
                Sign In with Github
              </button>
            </div>
          </div>
        </form>
        <p>
          don&apos;t have account yet? <Link href="/register">Sign Up</Link>
        </p>
      </div>
    </Layout>
  );
};

export default Login;
