import Head from "next/head";
import Link from "next/link";
import React from "react";
import Layout from "../components/layout/layout";
import { useForm, SubmitHandler } from "react-hook-form";
import { signIn } from "next-auth/react";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";

const FormSchema = z.object({
  email: z.string().email().min(2),
  password: z.string().min(6),
});

type SchemaType = z.infer<typeof FormSchema>;

const Login = () => {
  const {
    register,
    handleSubmit,
    watch,
    reset,
    formState: { errors },
  } = useForm<SchemaType>({
    resolver: zodResolver(FormSchema),
  });

  const onSubmit: SubmitHandler<SchemaType> = (data) => console.log(data);
  console.log(watch("email"));
  console.log(watch("password"));

  return (
    <Layout>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Login</h1>

      <div>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div>
            <input type="email" placeholder="email" {...register("email")} />
            {errors.email?.message && <p>{errors.email?.message}</p>}
          </div>
          <div>
            <input
              type="password"
              placeholder="password"
              {...register("password")}
            />
            {errors.password?.message && <p>{errors.password?.message}</p>}
          </div>
          <div>
            <button type="submit">Login</button>
          </div>
          <hr />
          <div>
            <div>
              <button
                onClick={() =>
                  signIn("google", { callbackUrl: "http://localhost:3000" })
                }
                type="button"
              >
                Sign In with Google
              </button>
            </div>
            <div>
              <button
                onClick={() =>
                  signIn("github", { callbackUrl: "http://localhost:3000" })
                }
                type="button"
              >
                Sign In with Github
              </button>
            </div>
          </div>
        </form>
        <p>
          don&apos;t have account yet? <Link href="/register">Sign Up</Link>
        </p>
      </div>
    </Layout>
  );
};

export default Login;
