import Head from "next/head";
import Link from "next/link";
import React from "react";
import Layout from "../components/layout/layout";

const Register = () => {
  return (
    <Layout>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Register</h1>
      <div>
        <form>
          <div>
            <input type="text" name="username" placeholder="Username" />
          </div>
          <div>
            <input type="email" name="email" placeholder="Email" />
          </div>
          <div>
            <input type="password" name="password" placeholder="Password" />
          </div>
          <div>
            <input
              type="password"
              name="cpassword"
              placeholder="Confirm Password"
            />
          </div>
          <div>
            <button type="submit">Register</button>
          </div>
        </form>
        <p>
          have account yet? <Link href="/login">Sign In</Link>
        </p>
      </div>
    </Layout>
  );
};

export default Register;
